name: Lint Code

on: 
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Укажи нужную версию Ruby
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Slim-Lint
        run: bundle exec slim-lint -c .slim-lint.yml